- name: This playbook will install nginx, configure nginx web root folder, deploy a custom html web page
  hosts: all
  become: yes
  vars:
  - provisioner_tool: Terraform
  - conf_mgr_tool: Ansible
  - greeting_msg: DevOps

  tasks:
  - name: Install nginx in Ubuntu Ansible nodes
    apt: name=nginx state=latest update_cache=yes

  - name: Created custom web root folder
    file: path=/var/html mode=0755 state=directory 

  - name: Deploy custom html web page 
    template: src=index.html.j2 dest=/var/html/index.html
 
  - name: Configure nginx web root folder
    copy: src=default dest=/etc/nginx/sites-available/default

  - name: Restart nginx web server
    service: name=nginx state=restarted
